from . import aafa_vendor_option
from . import res_partner_inherit
from . import product_template_inherit
from . import crossovered_budget_inherit
from . import account_inherit
from . import account_journal
from . import account_move_reversal
from . import inherited_res_user
from . import account_payment_inherit
from . import account_batch_payment_inherit
from . import account_move
from . import budget_approval_config
from . import budget_approval_line
from . import approve_info
from . import expense
from . import purchase_order